
import streamlit as st
import joblib
import pandas as pd
import os
import hashlib
import requests

# --- Configuration ---
# Path to your saved model
model_path = 'password_ai_model_v2.pkl'
# --- Load Model (Cached for performance) ---
@st.cache_resource
def load_model():
    model = None
    try:
        model = joblib.load(model_path)
        st.success("AI Model loaded successfully!")
    except FileNotFoundError:
        st.error(f"Error: Model file not found at {model_path}. Please ensure it's saved correctly.")
    except Exception as e:
        st.error(f"Error loading model: {e}")
    return model

model = load_model()

# --- Password Analysis Functions ---
def rate_password(password, model_obj):
    if not model_obj:
        return {"score": 0, "verdict": "Model not loaded. Cannot rate.", "raw_score": 0}

    length = len(password)
    upper = sum(1 for c in password if c.isupper())
    lower = sum(1 for c in password if c.islower())
    digits = sum(1 for c in password if c.isdigit())
    symbols = sum(1 for c in password if not c.isalnum())

    features = pd.DataFrame([[length, upper, lower, digits, symbols]],
                            columns=['length', 'num_uppercase', 'num_lowercase', 'num_digits', 'num_symbols'])

    score = model_obj.predict_proba(features)[0][1]
    strength_percentage = round(score * 100, 1)

    verdict = "WEAK (or fits hacker patterns) ❌"
    if score > 0.8:
        verdict = "STRONG 💪"
    elif score > 0.5:
        verdict = "MODERATE ⚠️"

    return {"score": strength_percentage, "verdict": verdict, "raw_score": score}

def is_pwned(password):
    """Checks if a password has been pwned using the HIBP k-Anonymity API."""
    try:
        sha1_password = hashlib.sha1(password.encode('utf-8')).hexdigest().upper()
        prefix, suffix = sha1_password[:5], sha1_password[5:]

        url = f"https://api.pwnedpasswords.com/range/{prefix}"
        response = requests.get(url, timeout=5)

        if response.status_code != 200:
            return False

        hashes = (line.split(':') for line in response.text.splitlines())
        for h, count in hashes:
            if h == suffix:
                return int(count)
        return False
    except Exception:
        return False

# --- Streamlit UI ---
st.set_page_config(page_title="Password Security Analyzer", layout="centered")

st.title("🔐 Password Security Analyzer")
st.markdown("Enter a password to check its strength and see if it has been exposed in data breaches (like 'Have I Been Pwned').")

user_password = st.text_input("Enter your password here:", type="password", help="Your password is not stored.")

if user_password:
    st.subheader("Analysis Results:")

    # Check if pwned using the HIBP API
    breach_count = is_pwned(user_password)

    if breach_count:
        st.error(f"❌ **OH NO! This password has been found {breach_count} times in known data breaches!**\n\nChange this password immediately on all accounts where you use it.")
    else:
        st.success("✅ Good news! This password has NOT been found in known data breaches.")

    # Rate strength using the AI model
    st.markdown("--- ")
    st.subheader("AI Strength Rating:")
    rating_results = rate_password(user_password, model)

    st.write(f"**Strength Score:** {rating_results['score']} / 100")
    st.write(f"**Verdict:** {rating_results['verdict']}")

    if rating_results['raw_score'] < 0.5:
        st.info("💡 **Tip:** Weak passwords often lack length, variety in characters (uppercase, lowercase, numbers, symbols), and are commonly used phrases or dictionary words. Try making it longer and more complex!")
    elif rating_results['raw_score'] < 0.8:
        st.info("💡 **Tip:** Moderate passwords are okay, but can often be improved with more length, a greater mix of character types, or by avoiding predictable patterns.")
    else:
        st.info("👍 **Tip:** This is a strong password! Keep up the good practices.")

st.markdown("--- ")
st.info("**Disclaimer:** This tool provides an estimate of password strength and breach status based on available data. For ultimate security, always use unique, long, and complex passwords generated by a trusted password manager.")
